Server will load successfully now but pages will not load due to "'NoneType' object has no attribute 'get"
	Traceback:
	Request Method: GET
	Request URL: http://127.0.0.1:8000/admin/

	Django Version: 1.11.1
	Python Version: 3.5.2
	Installed Applications:
	['django.contrib.admin',
	'django.contrib.auth',
	'django.contrib.contenttypes',
	'django.contrib.sessions',
	'django.contrib.messages',
	'django.contrib.staticfiles',
	'post.apps.PostConfig',
	'audiofield',
	'storages']
	Installed Middleware:
	['django.middleware.security.SecurityMiddleware',
	'django.contrib.sessions.middleware.SessionMiddleware',
	'django.middleware.common.CommonMiddleware',
	'django.middleware.csrf.CsrfViewMiddleware',
	'django.contrib.auth.middleware.AuthenticationMiddleware',
	'django.contrib.messages.middleware.MessageMiddleware',
	'django.middleware.clickjacking.XFrameOptionsMiddleware',
	'django-audiofield.audiofield.middleware.threadlocals.ThreadLocals']

	Traceback:

	File "/home/ewhitbeck/.virtualenvs/swampwalk/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
	41.             response = get_response(request)

	File "/home/ewhitbeck/.virtualenvs/swampwalk/lib/python3.5/site-packages/django/utils/deprecation.py" in __call__
	142.             response = self.process_response(request, response)

	File "/home/ewhitbeck/.virtualenvs/swampwalk/lib/python3.5/site-packages/django/middleware/clickjacking.py" in process_response
	32.         if response.get('X-Frame-Options') is not None:

	Exception Type: AttributeError at /admin/
	Exception Value: 'NoneType' object has no attribute 'get'